# Generated by Django 4.1.1 on 2022-09-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter the book natural language(e.g English, French, Japanese etc.', max_length=200, unique=True),
        ),
    ]
